# Denavit Hartenberg Notation

Kevin Walchko
Created: 10 July 2017

---

DH is an attempt to standardize how we represent serial manipulators (i.e., robot arms). It is typically one of the first ways you learn. It is really easy (methodical) to do forward kinematics, but becomes more challenging when doing inverse kinematics.

## References

- [Wikipedia modified DH](https://en.wikipedia.org/wiki/Denavit%E2%80%93Hartenberg_parameters)
- [Wikipedia euler angles](https://en.wikipedia.org/wiki/Euler_angles#Tait.E2.80.93Bryan_angles)
- [darpa robot challenge](https://www.youtube.com/watch?v=diaZFIUBMBQ)
- [darpa robot fails](https://youtu.be/wX0KagJ1du8)
- [Walking robot](https://vimeo.com/194676675)

## Setup

In [1]:
%matplotlib inline

In [35]:
from __future__ import print_function
from __future__ import division
import numpy as np
import sympy
from sympy import symbols, sin, cos, pi, simplify, trigsimp
from math import radians as d2r
from math import degrees as r2d
from math import atan2, sqrt, acos, fabs
from pprint import pprint
from IPython.display import HTML

# Kinematics

Robot arms and legs are hard to control (lots of math), but required for most robotic applications. Kinematics is the study of motion without regard to the forces which cause it. Kinematics of manipulators involves the study of the geometric and time based properties of the motion, and in particular how the various links move with respect to one another and with time.

## Coordinate Frames

We want to describe positions and orientations of bodies in space

- We generally draw a simplified version of the manipulator and attach a “frame” to each rigid body
    - The simplified version only has:
        - *Revolute joints:* joints that rotate
        - *Prismatic joints:* joints that move linearly (think telescoping)
    - By combining these in various combinations, we can make anything. For example, a spherical joint (ball-and-socket like your shoulder) is generally composed of 3 co-located (not physically real) rotational joints. This makes the math easier.
- The frame follows the serial manipulator's body
- There's some freedom in how we choose the frame's position and orientation relative to the body
- DH notation partially standardises, however, there are normal DH parameters and modified DH parameters. We are using modified (see reading in Craig)
- The combination of position and orientation of a frame is its “pose” ... like in fashion, "strike a pose"

An example (sort of) is shown below. Notice the real robot is represented as a simpler drawing of little metal bars:

![](dh_pics/kuka-kr270.png)

The KR270 has 6 joints and is a standard industrial type robot for building cars or what not. Notice again, the wrist, is represented as 2 revolute joints co-located (on top of each other) which is not realistic.

## Coordinate Systems

**get pics**

- A frame's pose only makes sense relative to another frame, e.g. hand pose relative to forearm pose...
- All of our frames will be a righthand-coordinate system (RHS) ... sorry lefties
- Everything is relative to some *global* frame
    - aka the “inertial frame”
- There is some freedom in choosing the *global* frame. However, this is usually a **non-moving** frame (e.g., inertial) and it is typically located some place convenient (i.e., make the math simplier)

## Euler Angles

![](dh_pics/euler.png)

Euler angles describe the moving frame and not the fixed (inertial) frame. They follow the sequence:

- rotate about the z-axis
- rotate about (the new) y-axis
- rotate about (the new) x-axis

Please notice, each rotation is dependant on previous rotations.

\begin{eqnarray}
  R_{\phi,x} = \begin{bmatrix}
    \cos(\phi) & -\sin(\phi) & 0 \\
    \sin(\phi) & \cos(\phi) & 0 \\
    0 & 0 & 1
  \end{bmatrix} \\
  R_{\theta,y} = \begin{bmatrix}
    \cos(\theta) & -\sin(\theta) & 0 \\
    \sin(\theta) & \cos(\theta) & 0 \\
    0 & 0 & 1
  \end{bmatrix} \\
  R_{\theta,z} = \begin{bmatrix}
    \cos(\theta) & -\sin(\theta) & 0 \\
    \sin(\theta) & \cos(\theta) & 0 \\
    0 & 0 & 1
  \end{bmatrix} \\
\end{eqnarray}

Now, for this class, we are not going to use these here (but you will see them pop-up in later lessons). A nice thing about these rotation matricies, is:

$$
R^B_A = (R^A_B)^T = (R^A_B)^{-1}
$$

This is because they are orthonormal (the dot product of the x, y, and z components is 0). This a matrix inverse and matrix transpose produce the same results, which is good since matrix inverse is CPU intensive compared to a matrix transpose.

$$
R = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9
\end{bmatrix} \\
R^T = \begin{bmatrix}
  1 & 4 & 7 \\
  2 & 5 & 8 \\
  3 & 6 & 9
\end{bmatrix}
$$

Notice transpose just turns matrix columns into matrix rows ... no math!

## Position and Orientation

![](dh_pics/frame1.PNG)

Now the position/orientation, or pose, of {B} relative to {A} is:

$$
P^A = R^A_B P^B
$$

Now ultimately, we want to know the location of a point in {B} relative to an inertial frame (say the base of our robot arm) in {A}.

![](dh_pics/frame2.png)

![](dh_pics/frame3.png)

What the final equation is saying, is, the position of P in frame A is equal to the offset between {A} and {B} (i.e., $P^A_B$) plus the change in orientation between {A} and {B} (i.e., $R^A_B P^B$). 

A compact representation of the translation and rotation is known as the **Homogeneous Transformation**. This allows us to cast the rotation and translation of the general transform in a single matrix form.

$$
T^A_B = \begin{bmatrix}
   & R^A_B & & P^A_B \\
  0 & 0 & 0 & 1
\end{bmatrix} \\
\begin{bmatrix}
  P^A \\
  1
\end{bmatrix} = 
T^A_B
\begin{bmatrix}
  P^B \\
  1
\end{bmatrix}
$$

This compact notation allows us to use `numpy` or `matlab` to write series of equations as matricies and do standard matrix operations on them. Now, as we attach frames to serial manipulator links, we will be able to combine these matricies together to calculate where the end effector is.

![](dh_pics/frame4.png)

## Craig Reading

Craig has similar notation, but changes a few things:

- homogenious transform is H instead of T
- the translation from {A} to {B} is $O^A_B$ (think O for origin) and not P

It seems like every author changes some little thing, but they are all similar.

# Denavit-Hartenberg (DH)

Development of the DH forward kinematics for a robot. We will use the DH method to develop the symbolic equations and use python to simplify them.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/DHParameter.png/609px-DHParameter.png)

## Process (Craig, section 3.2.3)

Now using ideas from before (see Craig, eqns 3.4 and 3.6):

| | | |
|------------|:---------|:------------------------------------------------------|
| $a_i$      | length   | distance from $z_i$ to $z_{i+1}$ measured along $x_i$ |
| $d_i$      | offset   | distance from $x_{i-1}$ to $x_i$ along $z_i$          |
| $\alpha_i$ | twist    | angle from $z_i$ to $z_{i+1}$ measured about $x_i$    |
| $\theta_i$ | rotation | angle from $x_{i−1}$ to $x_i$ measured about $z_i$    |

Summary of steps:

1. Identify the joint axes and imagine (or draw) infinite lines along them. For steps 2 through 5 below, consider two of these neighboring lines (at axes i and i+1).
1. Identify the comon perpendicular betwen them,or point of intersection. At the point of intersection, or at the point where the comon perpendicular mets the ith axis, asign the link-frame origin.
1. Asign the Z1 axis pointing along the ith joint axis.
1. A sign the axis pointing along the comon perpendicular, or, if the axes intersect, a sign k1 to be normal to the plane containing the two axes.
1. Asign the axis to complete a right-hand cordinate system. 
1. Asign {0} to match {1} when the first joint variable is zero. For {N}, chose an origin location and XN direction freely, but generaly so as to cause as many linkage parameters as possible to become zero.

$$
\begin{eqnarray}
T^{i-1}_i = R_x(\alpha_{i-1}) D_x(a_{i-1}) R_z(\theta_i) D_z(d_i) \\
T^{i-1}_i = \begin{bmatrix}
  \cos(\theta_i)                   & -\sin(\theta_i)                  & 0                   & a_{i-1} \\
  \sin(\theta_i)\cos(\alpha_{i-1}) & \cos(\theta_i)\cos(\alpha_{i-1}) & -\sin(\alpha_{i-1}) & -\sin(\alpha_{i-1})d_i \\
  \sin(\theta_i)\sin(\alpha_{i-1}) & \cos(\theta_i)\sin(\alpha_{i-1}) & \cos(\alpha_{i-1})  & \cos(\alpha_{i-1})d_i \\
  0                                & 0                                & 0                   & 1
\end{bmatrix}
\end{eqnarray}
$$

In [ ]:
HTML('<iframe src="https://player.vimeo.com/video/238147402" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><p><a href="https://vimeo.com/238147402">Denavit&ndash;Hartenberg parameters</a> from <a href="https://vimeo.com/user59907133">kevin</a> on <a href="https://vimeo.com">Vimeo</a>.</p>')

## Simple 2D Example

Following the process for assigning frames to a manipulator, you get the following:

![](dh_pics/2d-ex.png)

Looking at the above frames, they are related by:

| Link | $a_{i-1}$ | $\alpha_{i-1}$ | $d_i$ | $\theta_i$ |
|------|-----------|----------------|-------|------------|
| 1    | $a_1$ | 0          | 0     | $\theta_1$ |
| 2    | $a_2$ | 0          | 0     | $\theta_2$ |

Now using Craig eqn 3.6, we can substitute these values in and get the relationship between the inertial frame and the end effector. However note, $\theta_i$ are variable parameters. Typically we want to (but if computational speed isn't important) would simplify these equations down leaving only the theta parameters.

In [17]:
def makeT(a, alpha, d, theta):
    # modified DH homogenious matrix
    return np.array([
        [           cos(theta),           -sin(theta),           0,             a],
        [sin(theta)*cos(alpha), cos(theta)*cos(alpha), -sin(alpha), -d*sin(alpha)],
        [sin(theta)*sin(alpha), cos(theta)*sin(alpha),  cos(alpha),  d*cos(alpha)],
        [                    0,                     0,           0,             1]
    ])

In [42]:
def simplifyT(tt):
    for i, row in enumerate(tt):
        for j, col in enumerate(row):
            tt[i,j] = simplify(col)
    return tt

def subs(tt, m):
    """
    This allows you to simplify the trigonomic mess that kinematics can
    create and also substitute in some inputs in the process
    """
    for i, row in enumerate(tt):
        for j, col in enumerate(row):
            try:
                tt[i,j] = col.subs(m)
            except:
                tt[i,j] = col
    return tt

In [46]:
# make thetas (t) and link lengths (a) symbolics
t1, t2 = symbols('t1 t2')
a1, a2 = symbols('a1 a2')

T1 = makeT(a1, 0, 0, t1)
T2 = makeT(a2, 0, 0, t2)
T12 = T1.dot(T2)
# print(T0)
print(T1)
# print(subs(T1, [(t1, 0), (t2, 0)]))
print(T2)
print(T12)
# print(subs(T12, [(t1, 0), (t2, 0)]))
ans = simplify(T12)
print(ans)
print('-'*25)
print('wrong', simplifyT(T2.dot(T1)))

[[cos(t1) -sin(t1) 0 a1]
 [sin(t1) cos(t1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[cos(t1 + t2) -sin(t1 + t2) 0 a2]
 [sin(t1 + t2) cos(t1 + t2) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[-sin(t1)*sin(t1 + t2) + cos(t1)*cos(t1 + t2)
  -sin(t1)*cos(t1 + t2) - sin(t1 + t2)*cos(t1) 0 a1 + a2*cos(t1)]
 [sin(t1)*cos(t1 + t2) + sin(t1 + t2)*cos(t1)
  -sin(t1)*sin(t1 + t2) + cos(t1)*cos(t1 + t2) 0 a2*sin(t1)]
 [0 0 1 0]
 [0 0 0 1]]
[[cos(2*t1 + t2), -sin(2*t1 + t2), 0, a1 + a2*cos(t1)], [sin(2*t1 + t2), cos(2*t1 + t2), 0, a2*sin(t1)], [0, 0, 1, 0], [0, 0, 0, 1]]
-------------------------
wrong [[cos(2*t1 + t2) -sin(2*t1 + t2) 0 a1*cos(t1 + t2) + a2]
 [sin(2*t1 + t2) cos(2*t1 + t2) 0 a1*sin(t1 + t2)]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
# craig problem 3.9 p 95
# t1, t3 = symbols('t1 t2')
# d2, L2 = symbols('d2 L2')

T01 = makeT(L1, 0, 0, t1)
T12 = makeT(0, pi/2, 0, t2)

ans = simplifyT(T01.dot(T12))
print(ans)

[[cos(t1)*cos(t2) -sin(t2)*cos(t1) sin(t1) L1]
 [sin(t1)*cos(t2) -sin(t1)*sin(t2) -cos(t1) 0]
 [sin(t2) cos(t2) 0 0]
 [0 0 0 1]]


In [16]:
# craig puma
t1,t2,t3,t4,t5,t6 = symbols('t1 t2 t3 t4 t5 t6')
a2, a3, d3, d4 = symbols('a2 a3 d3 d4')

T01 = makeT(0,0,0,t1)
T12 = makeT(0,-pi/2,0,t2)
T23 = makeT(a2,0,d3,t3)
T34 = makeT(a3,-pi/2,d4,t4)
T45 = makeT(0,pi/2,0,t5)
T56 = makeT(0,-pi/2,0,t6)

# print(T45)
# print(T56)
# print(T45.dot(T56))

ans = simplifyT(T34.dot(T45.dot(T56)))
print(ans)

[[-sin(t4)*sin(t6) + cos(t4)*cos(t5)*cos(t6)
  -sin(t4)*cos(t6) - sin(t6)*cos(t4)*cos(t5) -sin(t5)*cos(t4) a3]
 [sin(t5)*cos(t6) -sin(t5)*sin(t6) cos(t5) d4]
 [-sin(t4)*cos(t5)*cos(t6) - sin(t6)*cos(t4)
  sin(t4)*sin(t6)*cos(t5) - cos(t4)*cos(t6) sin(t4)*sin(t5) 0]
 [0 0 0 1]]


| | |
|------------|:------------------------------------------------------|
| $a_i$      | distance from $z_i$ to $z_{i+1}$ measured along $x_i$ |
| $d_i$      | distance from $x_{i-1}$ to $x_i$ along $z_i$          |
| $\alpha_i$ | angle from $z_i$ to $z_{i+1}$ measured about $x_i$    |
| $\theta_i$ | angle from $x_{i−1}$ to $x_i$ measured about $z_i$    |

Summary of steps:

1. Identify the joint axes and imagine (or draw) infinite lines along them. For steps 2 through 5 below, consider two of these neighboring lines (at axes i and i+1).
1. Identify the comon perpendicular betwen them,or point of intersection. At the point of intersection, or at the point where the comon perpendicular mets the ith axis, asign the link-frame origin.
1. Asign the Z1 axis pointing along the ith joint axis.
1. A sign the axis pointing along the comon perpendicular, or, if the axes intersect, a sign k1 to be normal to the plane containing the two axes.
1. Asign the axis to complete a right-hand cordinate system. 
1. Asign {0} to match {1} when the first joint variable is zero. For {N}, chose an origin location and XN direction freely, but generaly so as to cause as many linkage parameters as possible to become zero.

## Numerical Forward Kinematics

---

## Symbolically Solving Forward Kinematics

The following class follows the modified [DH convention](https://en.wikipedia.org/wiki/Denavit%E2%80%93Hartenberg_parameters). Where:

| Parameter | Definition|
|-----------|-----------|
| $\alpha_i$   | angle about common normal, from old z axis to new z axis (twist)|
| $d_i$        | offset along previous z to the common normal |
| $\theta_i$   | angle about previous z, from old x to new x |
| $a_i$        | length of the common normal. Assuming a revolute joint, this is the radius about previous z. |

Now the transformation matrix ($T$), using modified DH parameters, is given by:

$$ T = R_x(\alpha_{n-1}) D_x(a_{n-1}) R_z(\theta_n) D_z(d_n) $$

We can then turn this into a python class as follows:


-----------

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.