# Intro to numpy and sympy

Kevin J. Walchko
created 5 July 2017

---

NumPy and pysym are open-source add-on modules to Python that provide common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that associated with common commercial software like MatLab. There is little that Matlab can do that python, numpy and other modules can't do too.

- [numpy tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
- [numpy for matlab users](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html)
- [sympy](http://www.sympy.org/en/index.html)
- [sympy tutorials](http://docs.sympy.org/latest/tutorial/index.html)


In [47]:
from __future__ import division
from __future__ import print_function
import numpy as np  # common to rename numpy to np ... because programmers are lazy

# Numpy

In [48]:
# lets create an array
a = np.array([1,2,3])  # you could call this a 3 dimensional vector if you want
print(a)

[1 2 3]


In [49]:
# let's create a matrix
m = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
print(m)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [50]:
# let's multiply them together
v = m.dot(a)
print(v)

[14 32 44]


In [51]:
# let's access the number of each ... all zero based arrays
print('first v:', v[0])
print('first m:', m[0,0])

# now let's do the last number
print('last v:', v[2])
print('last m:', m[2,2])

# let's get their dimensions
print('len(a):', len(a))
print('m.shape:', m.shape)
print('a.shape:', a.shape)

first v: 14
first m: 1
last v: 44
last m: 8
len(a): 3
m.shape: (3, 3)
a.shape: (3,)


In [52]:
n = np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

# inverse
nn = np.linalg.inv(n)
print(nn)

# calculate the determinate
nn = np.linalg.det(n)
print(nn)

# calculate the norm
nn = np.linalg.norm(n)
print(nn)

[[ 1.          0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          0.33333333]]
6.0
3.74165738677


In [53]:
# too much typing ... let's shorten it
# just becareful not to alias another python function
# 
from numpy.linalg import inv, det, norm

# inverse
nn = inv(n)
print(nn)

# calculate the determinate
nn = det(n)
print(nn)

# calculate the norm
nn = norm(n)
print(nn)

[[ 1.          0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          0.33333333]]
6.0
3.74165738677


In [54]:
# just becareful not to alias another python function
# numpy abs and standard python abs are an example
# however
import numpy
help(numpy.abs)

Help on ufunc object:

absolute = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, 

In [55]:
# let's see what else is in linalg
dir(numpy.linalg)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 '_umath_linalg',
 'absolute_import',
 'bench',
 'cholesky',
 'cond',
 'det',
 'division',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'info',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'print_function',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [56]:
# let's iterate over a matrix and print each value out
mm, nn = m.shape
for i in range(mm):
    for j in range(nn):
        print('m[{}, {}] = {}'.format(i,j,m[i,j]))


print('')
print(m)

m[0, 0] = 1
m[0, 1] = 2
m[0, 2] = 3
m[1, 0] = 4
m[1, 1] = 5
m[1, 2] = 6
m[2, 0] = 6
m[2, 1] = 7
m[2, 2] = 8

[[1 2 3]
 [4 5 6]
 [6 7 8]]


# Sympy

You can use sympy to manipulate equations symbolically. This will be useful later when we do forward/inverse kinematics.

In [57]:
from sympy import symbols, sin, cos, pi, simplify

In [58]:
# create some symbols and a symbolic equation
a, b = symbols('a b')
eqn = sin(a)*sin(a)+cos(a)**2+sin(b)/cos(b) + a
print(eqn)

a + sin(a)**2 + sin(b)/cos(b) + cos(a)**2


In [59]:
# simplify the equations
e = simplify(eqn)
print(e)

a + tan(b) + 1


In [60]:
# substitute in some numbers for a and b
ee=e.subs([(b, 2.0), (a, 3.0)])
print(ee)

1.81496013673848


In [61]:
# this should give us the same answer
import math
3.0+math.tan(2.0)+1.0

1.8149601367384811


-----------

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.