# Introduction to `numpy` and `sympy` - combine w/matplotlib?

Kevin J. Walchko
created 5 July 2017

---

NumPy and pysym are open-source add-on modules to Python that provide common mathematical and numerical routines in pre-compiled, fast functions. These are growing into highly mature packages that provide functionality that meets, or perhaps exceeds, that associated with common commercial software like MatLab. There is little that Matlab can do that python, numpy and other modules can't do too.

## Objectives

- Understand how to do very basic linear algebra in python
- Understand how to do symbolic manipulation in python

## References

- [numpy tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
- [numpy for matlab users](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html)
- [sympy](http://www.sympy.org/en/index.html)
- [sympy tutorials](http://docs.sympy.org/latest/tutorial/index.html)

## Setup

In [1]:
from __future__ import division
from __future__ import print_function
import numpy as np  # common to rename numpy to np ... because programmers are lazy :)

# Numpy

First let's do some simple matrix/vector operations, since we will need this for our serial manipulator work. We will also use `numpy` later for OpenCV imagery work, but we will push that off to later when we need it. There are some specific things we need  to understand when working with images that would be best covered right before we need it.

In [6]:
# there are a number of standard matricies used in math/engineering:
# zeros = all elements of the matrix are 0
z = np.zeros((3,3))
print('zeros\n', z)

# ones = all elements of the matrix are 1
o = np.ones((3,3))
print('ones\n', o)

# eye = this is the identity matrix. Anything multiplied by it comes out the same: A = I * A
i = np.eye(3,3) # note, you don't pass a tuple to it ... annoying interface change!!!
print('eye\n', i)

zeros
 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
ones
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
eye
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [26]:
# numpy even works in multiple dimension beyond standard 2x2 matrices
np.zeros((3,4,5)) # go on and add some more dimentions like: (3,3,3,3)

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [7]:
# lets create an array
a = np.array([1,2,3])  # you could call this a 3 dimensional vector if you want
print(a)

[1 2 3]


In [8]:
# let's create a matrix
m = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
print(m)
print('size', m.size)
print('shape', m.shape)
print('type', m.dtype)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
size 9
shape (3L, 3L)
type int32


Now, generally we don't think about data types with python, but for math (and later working with images in OpenCV) we will. *Note:* you will probably have to prefix these with a namespace like `np`: `np.uint8`. This assumes you did the `import numpy as np`. 

| Data type	| Description |
|---|:---|
| bool_	| Boolean (True or False) stored as a byte
| int_	| Default integer type (same as C long; normally either int64 or int32)
| intc	| Identical to C int (normally int32 or int64)
| intp	| Integer used for indexing (same as C ssize_t; normally either int32 or int64)
| int8	| Byte (-128 to 127)
| int16	| Integer (-32768 to 32767)
| int32	| Integer (-2147483648 to 2147483647)
| int64	| Integer (-9223372036854775808 to 9223372036854775807)
| uint8	| Unsigned integer (0 to 255)
| uint16 | Unsigned integer (0 to 65535)
| uint32 | Unsigned integer (0 to 4294967295)
| uint64 | Unsigned integer (0 to 18446744073709551615)
| float_ | Shorthand for float64.
| float16 | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
| float32 | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
| float64 | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
| complex_ | Shorthand for complex128.
| complex64	| Complex number, represented by two 32-bit floats (real and imaginary components)
| complex128 | Complex number, represented by two 64-bit floats (real and imaginary components)

In [9]:
# let's multiply them together
v = m.dot(a)
print(v)

[14 32 44]


In [10]:
# let's access the number of each ... all zero based arrays
print('first v:', v[0])
print('first m:', m[0,0])

# now let's do the last number
print('last v:', v[2])
print('last m:', m[2,2])

# let's get their dimensions
print('len(a):', len(v))
print('v.shape:', v.shape)
print('m.shape:', m.shape)

first v: 14
first m: 1
last v: 44
last m: 8
len(a): 3
v.shape: (3L,)
m.shape: (3L, 3L)


In [11]:
n = np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

# inverse
nn = np.linalg.inv(n)
print(nn)

# calculate the determinate
nn = np.linalg.det(n)
print(nn)

# calculate the norm
nn = np.linalg.norm(n)
print(nn)

[[ 1.          0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          0.33333333]]
6.0
3.74165738677


In [12]:
# too much typing ... let's shorten it
# just becareful not to alias another python function ... python for example
# already has a built in abs (absolute) function, but so numpy
from numpy.linalg import inv, det, norm

# inverse
nn = inv(n)
print('in', nn)

# calculate the determinate
nn = det(n)
print('det', nn)

# calculate the norm
nn = norm(n)
print('norm', nn)

in [[ 1.          0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          0.33333333]]
det 6.0
norm 3.74165738677


In [13]:
# let's iterate over a matrix and print each value out
mm, nn = m.shape
for i in range(mm):
    for j in range(nn):
        print('m[{}, {}] = {}'.format(i,j,m[i,j]))

print('')
print(m)

m[0, 0] = 1
m[0, 1] = 2
m[0, 2] = 3
m[1, 0] = 4
m[1, 1] = 5
m[1, 2] = 6
m[2, 0] = 6
m[2, 1] = 7
m[2, 2] = 8

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [14]:
# we can do it another way
# also, enumerate is a nice way to get a counter
for i, r in enumerate(m):
    for j, c in enumerate(r):
        print('m[{}, {}] = {}'.format(i,j,c))

m[0, 0] = 1
m[0, 1] = 2
m[0, 2] = 3
m[1, 0] = 4
m[1, 1] = 5
m[1, 2] = 6
m[2, 0] = 6
m[2, 1] = 7
m[2, 2] = 8


## Documentation

If you don't understand what a function does, Google it or (like all python libraries) use the built in help system: `help(numpy.inv)`. 

You can also find out what is availble in a  package by: `dir(numpy)`. This would list everything in `numpy`. Or if you wanted to know what was in the linear algebra sub-package: `dir(numpy.linalg)`.

# Sympy

You can use sympy to manipulate equations symbolically. This will be useful later when we do forward/inverse kinematics.

In [16]:
from sympy import symbols, sin, cos, pi, simplify

In [17]:
# create some symbols and a symbolic equation
a, b = symbols('a b')
eqn = sin(a)*sin(a)+cos(a)**2+sin(b)/cos(b) + a
print(eqn)

a + sin(a)**2 + sin(b)/cos(b) + cos(a)**2


In [18]:
# simplify the equations
# s^2 + c^2 = 1
# s/c = tan
e = simplify(eqn)
print(e)

a + tan(b) + 1


In [19]:
# substitute in some numbers for a and b
ee=e.subs([(b, 2.0), (a, 3.0)])
print(ee)

1.81496013673848


In [20]:
# this should give us the same answer
import math
3.0+math.tan(2.0)+1.0

1.8149601367384811


-----------

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.